M48
; DRILL file {KiCad 9.0.3} date 2025-10-17T16:04:43+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-17T16:04:43+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C5.300
%
G90
G05
T1
X108.75Y-76.67
T2
X90.97Y-42.38
X90.97Y-123.66
X172.25Y-42.38
X172.25Y-123.66
M30
